### ISSUE TITLE
Use builder pattern for model creation

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#210] opened 2023-03-07 20:33 UTC
### Feature description

Similar to `LearnerBuilder`, there should be builders for NN modules, such as `Conv2d`.  

### Feature motivation

Currently there two separate steps for defining nn module (config and construction). It would be easier if the user could use one step without passing complex config parameters. 

### (Optional) Suggest a Solution

It would great if the user could do this:

```rust

let conv = Conv2dBuilder()
        .withChannels([1,16])
        .withKernel([3,3])
        .build();

// OR

let builder = Conv2dBuilder()
              .withKernel([3,3])
              .withBias(false);


let conv1 = builder.withChannels([1,16]).build();
let conv2 = builder.withChannels([16,32]).build();
let conv3 = builder.withChannels([32,48]).build();

```

### Action Item
- [ ] Update examples/mnist-inference-web to remove random initialization

**Comment by nathanielsimard** [comment] 2023-03-09 21:27
The builder pattern is already implemented for configs, and I really want to put emphasis on using serializable hyper-parameters. However, we could still improve the API with an `init` function:

```rust
let conv = Conv2dConfig::new(1, 3) // Required arguments
                   .with_bias(false)
                   .init();
```

This would be a new Trait to be implemented by Module with something like:

```rust
// The derive can add `init()` to `Conv2dConfig` that dispatch to the `Initialize` trait.
#[derive(Module(config = "Conv2dConfig"))] 
pub struct Conv2d{
   ...
}

impl<B: Backend> Initialize<B> for Conv2d<B> {
    type Config = Conv2dConfig;
    
    fn init(config: &Self::Config) -> Self {
        ...
    }
    /// It would be cool to have an optional `init_state` function that would, by default, use the `init` method.
    fn init_state(state: &State<B::FloatElem>, config: &Self::Config) -> Self {
       ...
    }
}
```

We could require every module to implement `Initialize` and force them to have an associative type `Config`. With this, we could avoid having to initialize a module just before loading the weights (waste), which could reduce cold starts.

**Comment by nathanielsimard** [comment] 2023-03-22 13:22
Ho I forgot that you can't have arguments in derive macros. After consideratino, I think we should just implement `From`.

```rust
impl<B: Backend> From<ModuleConfig> for Module {
...
}
```
It automatically generate the into method, so you could have:

```rust
let module: Module = ModuleConfig::new(...).into();
```

What I like about it is that it's very Rusty and you can have multiple `From` implementations for the same module. Which means that we could also implement:

```rust
impl<B: Backend> From<(ModuleConfig, State)> for Module {
...
}
```

So instead of initializing a new module, it creates a new module with the given weights.

```rust
let module: Module = (ModuleConfig:new(...), state).into();
// or
let module = Module::from((ModuleConfig::new(...), state));
```
It's a bit less pretty than the previous use case, since you have a tuple, but it's easy to understand I think.

**Comment by antimora** [comment] 2023-03-22 18:23
@nathanielsimard 

I feel like using from and into is a bit overloaded here. I think of `into` and `from` are used transform to a similar/sister structure but here we are trying to use a configuration to build a module.

Why is it necessary to do `#[derive(Module(config = "Conv2dConfig"))] `?

Can we just do this?
```rust
impl<B: Backend> Initialize<B> for Conv2dConfig<B> {
    type Module = Conv2d;
    
    fn init(&self) -> Module {
        ...
    }
    fn init_state(&self, state: State) -> Module {
       ...
    }
}

```

It's similar as implementing `From`.

**Comment by nathanielsimard** [comment] 2023-03-23 15:44
The thing that bothers me with this is that some modules may need something else then the config to be initialized. For example, some modules may need shared parameters from another module before being initialized. So the `Initialize` trait would not fit that purpose. So do we need an abtraction for this knowing that not all modules will be able to implement it? I'm not sure.

Maybe we could just implement `init` and `init_state` on modules without being a trait. Also, the `Initialize` trait would not need to be imported to see the methods pop in autocomplete, maybe helping discoverability.

**Comment by antimora** [comment] 2023-03-23 17:43
> Maybe we could just implement `init` and `init_state` on modules without being a trait. Also, the `Initialize` trait would not need to be imported to see the methods pop in autocomplete, maybe helping discoverability.

Do you mean  `init` and `init_state` on *Config structs? Are we still able to do this?

```rust
let conv = Conv2dConfig::new(1, 3) // Required arguments
                   .with_bias(false)
                   .init();
```

with we can do this too:

```rust
let conv_config = Conv2dConfig::new(1, 3) // Required arguments
                   .with_bias(false);

let conv = conv_config.init(); 

// or 

let conv = conv_config.init_state(data); 


```

**Comment by nathanielsimard** [comment] 2023-03-23 20:11
Yes that's what I mean

**Comment by antimora** [comment] 2023-04-02 18:27
@nathanielsimard Where do we stand on this task? Will you have additional check-ins on top what of your merged PR?

**Comment by nathanielsimard** [comment] 2023-04-02 18:41
I think we need to be able to load a model with the sate before the issue is 100% completed, probably very soon.

**Comment by nathanielsimard** [comment] 2023-04-08 17:13
I'm closing this, since we have the `init` and `init_with` function on the config struct to build modules.

**Closed by nathanielsimard** 2023-04-08 17:13 UTC
Labels: feature
