### ISSUE TITLE
MNIST Inference Web Example not working on Mac M1

### ISSUE THREAD

**Issue by filopedraz** [burn-rs/burn#812] opened 2023-09-18 07:45 UTC
### Description

Trying to build the package with `build-for-web.sh` I get this error:

```txt
error[E0432]: unresolved import `burn::backend::ndarray`
 --> examples/mnist-inference-web/src/state.rs:2:20
  |
2 | use burn::backend::ndarray::NdArrayBackend;
  |                    ^^^^^^^ could not find `ndarray` in `backend`

warning: unused import: `burn::module::Module`
 --> examples/mnist-inference-web/src/state.rs:3:5
  |
3 | use burn::module::Module;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0432`.
warning: `mnist-inference-web` (lib) generated 1 warning
error: could not compile `mnist-inference-web` (lib) due to previous error; 1 warning emitted
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
```

### To Reproduce

```bash
cd ./examples/mnist-inference-web
bash ./build-for-web.sh
```

### Next Errors

I also tried to fix it, changing the dependency in `Cargo.toml` from `burn = {path = "../../burn", default-features = false, features = ["ndarray-no-std"]}` to `burn = {path = "../../burn", default-features = false, features = ["ndarray"]}`.

But I am getting another error

```txt
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /Users/filippopedrazzini/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:285:9
    |
285 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
286 | |                         default, you may need to enable the \"js\" feature. \
287 | |                         For more information see: \
288 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/filippopedrazzini/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:341:9
    |
341 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
```

From the doc pointed out by the compiler, they suggest to update add `getrandom = { version = "0.2", features = ["js"] }` in the `Cargo.toml` file.

```txt
This crate fully supports the [wasm32-wasi](https://github.com/CraneStation/wasi) and [wasm32-unknown-emscripten](https://www.hellorust.com/setup/emscripten/) targets. However, the wasm32-unknown-unknown target (i.e. the target used by wasm-pack) is not automatically supported since, from the target name alone, we cannot deduce which JavaScript interface is in use (or if JavaScript is available at all).

Instead, if the js Cargo feature is enabled, this crate will assume that you are building for an environment containing JavaScript, and will call the appropriate methods. Both web browser (main window and Web Workers) and Node.js environments are supported, invoking the methods [described above](https://docs.rs/getrandom/latest/getrandom/#supported-targets) using the [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) toolchain.
```

But getting another error

```txt
error: lto can only be run for executables, cdylibs and static library outputs

error: could not compile `burn-with-wasm` (lib) due to previous error
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
```

**Comment by antimora** [comment] 2023-09-18 15:15
Thanks for reporting it. I'll look into this since I worked on this previously. There must be have been some changes it broke it. 
I use Mac M1 as well.

**Comment by antimora** [comment] 2023-09-19 14:34
@filopedraz I could not reproduce the error. Can you please pull the latest changes and rebuild it? I suggest you cargo clean as well. We have had an issue with examples but it has been fixed, so it's possible your code is stale.

The second error that you came across is due to incorrect backend option selected. The backend needs to be no-std. The application does not use a random seed via JS API calls but it comes up in the compilation of std code for wasm32 target.

**Comment by antimora** [comment] 2023-09-21 19:45
Closing it for now. If you have any issue after an update, please feel free to reopen this ticket.

**Closed by antimora** 2023-09-21 19:45 UTC
Labels: bug

**Comment by L-M-Sherlock** [comment] 2023-10-12 08:35
I also meet a error when run `./build-for-web.sh wgpu`:

```
error: lto can only be run for executables, cdylibs and static library outputs

error: could not compile `walrus-macro` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `serde_derive` (lib) due to previous error
error: failed to compile `wasm-bindgen-cli v0.2.87`, intermediate artifacts can be found at `/var/folders/20/_t6_h0cx4nl1qr58y1km9l740000gn/T/cargo-install4IYCmZ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Error: Installing wasm-bindgen with cargo
Caused by: Installing wasm-bindgen with cargo
Caused by: failed to execute `cargo install`: exited with exit status: 101
  full command: "cargo" "install" "--force" "wasm-bindgen-cli" "--root" "/Users/jarrettye/Library/Caches/.wasm-pack/.wasm-bindgen-cargo-install-0.2.87" "--version" "0.2.87"
```

**Comment by antimora** [comment] 2023-10-12 19:01
@L-M-Sherlock, strange that you had to remove lto config. I have created a new ticket to investigate: https://github.com/burn-rs/burn/issues/860 If you have more information. please tack it on there.
