### ISSUE TITLE
Conv1d kernel setting bug

### ISSUE THREAD

**Issue by mrvollger** [burn-rs/burn#654] opened 2023-08-17 00:32 UTC
**Describe the bug**
Importing a working onnx model (working in pytorch) ends in an invalid matrix multiplication after flattening.

Here is the traceback:
```
thread 'predict_m6a::onnx::my_test' panicked at '=== Tensor Operation Error ===
  Operation: 'Matmul'
  Reason:
    1. The inner dimension of matmul should be the same, but got 75 and 25. Lhs shape [1, 75], rhs shape [25, 5]. 
', /Users/mrvollger/Desktop/repos/burn/burn-tensor/src/tensor/api/float.rs:196:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:150:5
   3: burn_tensor::tensor::api::float::<impl burn_tensor::tensor::api::base::Tensor<B,_>>::matmul
             at /Users/mrvollger/Desktop/repos/burn/burn-tensor/src/tensor/api/float.rs:196:9
   4: burn_core::nn::linear::Linear<B>::forward
             at /Users/mrvollger/Desktop/repos/burn/burn-core/src/nn/linear.rs:83:22
   5: fibertools_rs::model::revio::Model<B>::forward
             at ./target/debug/build/fibertools-rs-531f3735a2cf7cfe/out/model/revio.rs:115:28
   6: fibertools_rs::predict_m6a::onnx::my_model
             at ./src/predict_m6a/onnx.rs:18:18
   7: fibertools_rs::predict_m6a::onnx::my_test
             at ./src/predict_m6a/onnx.rs:25:13
   8: fibertools_rs::predict_m6a::onnx::my_test::{{closure}}
             at ./src/predict_m6a/onnx.rs:24:14
   9: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
And here is the model code generated for this by burn-import:
```
// Generated from ONNX "src/model/revio.onnx" by burn-import
use burn::nn::conv::Conv1d;
use burn::nn::conv::Conv1dConfig;
use burn::nn::Linear;
use burn::nn::LinearConfig;
use burn::nn::PaddingConfig1d;
use burn::record::Recorder;
use burn::{
    module::Module,
    tensor::{backend::Backend, Tensor},
};


#[derive(Module, Debug)]
pub struct Model<B: Backend> {
    conv1d1: Conv1d<B>,
    conv1d2: Conv1d<B>,
    conv1d3: Conv1d<B>,
    linear1: Linear<B>,
    linear2: Linear<B>,
    phantom: core::marker::PhantomData<B>,
}

impl<B: Backend> Default for Model<B> {
    fn default() -> Self {
        let record = burn :: record :: DefaultFileRecorder :: < burn :: record :: FullPrecisionSettings > :: new () . load ("/Users/mrvollger/Desktop/repos/fibertools-rs/target/debug/build/fibertools-rs-531f3735a2cf7cfe/out/model/revio" . into ()) . expect ("Record file to exist.") ;
        Self::new_with(record)
    }
}

impl<B: Backend> Model<B> {
    #[allow(unused_variables)]
    pub fn new_with(record: ModelRecord<B>) -> Self {
        let conv1d1 = Conv1dConfig::new(6, 30, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init_with(record.conv1d1);
        let conv1d2 = Conv1dConfig::new(30, 10, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init_with(record.conv1d2);
        let conv1d3 = Conv1dConfig::new(10, 5, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init_with(record.conv1d3);
        let linear1 = LinearConfig::new(25, 5)
            .with_bias(true)
            .init_with(record.linear1);
        let linear2 = LinearConfig::new(5, 2)
            .with_bias(true)
            .init_with(record.linear2);
        Self {
            conv1d1,
            conv1d2,
            conv1d3,
            linear1,
            linear2,
            phantom: core::marker::PhantomData,
        }
    }

    #[allow(dead_code)]
    pub fn new() -> Self {
        let conv1d1 = Conv1dConfig::new(6, 30, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let conv1d2 = Conv1dConfig::new(30, 10, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let conv1d3 = Conv1dConfig::new(10, 5, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let linear1 = LinearConfig::new(25, 5).with_bias(true).init();
        let linear2 = LinearConfig::new(5, 2).with_bias(true).init();
        Self {
            conv1d1,
            conv1d2,
            conv1d3,
            linear1,
            linear2,
            phantom: core::marker::PhantomData,
        }
    }

    #[allow(clippy::let_and_return)]
    pub fn forward(&self, input1: Tensor<B, 3>) -> Tensor<B, 2> {
        let conv1d1_out1 = self.conv1d1.forward(input1);
        let relu1_out1 = burn::tensor::activation::relu(conv1d1_out1);
        let conv1d2_out1 = self.conv1d2.forward(relu1_out1);
        let relu2_out1 = burn::tensor::activation::relu(conv1d2_out1);
        let conv1d3_out1 = self.conv1d3.forward(relu2_out1);
        let relu3_out1 = burn::tensor::activation::relu(conv1d3_out1);
        let flatten1_out1 = relu3_out1.flatten(1, 2);
        let linear1_out1 = self.linear1.forward(flatten1_out1);
        let relu4_out1 = burn::tensor::activation::relu(linear1_out1);
        let linear2_out1 = self.linear2.forward(relu4_out1);
        let softmax1_out1 = burn::tensor::activation::softmax(linear2_out1, 1);
        softmax1_out1
    }
}
```

**To Reproduce**
I tried to come up with a minimal example, but I am having difficulty doing so, so I am including the full onnx model (below) and the code I use to run it. I hope that is okay.

Load this onnx model using burn-import:
https://github.com/fiberseq/fibertools-rs/raw/onnx_burn/src/model/revio.onnx

And then test running the model with the following code:
```rust
use super::super::model::revio::Model;
use anyhow::Result;
use burn::tensor::backend::Backend;
use burn::tensor::{Shape, Tensor};
use burn_ndarray::NdArrayBackend;
type NdArrayB = NdArrayBackend<f32>;

pub fn my_model<B>() -> Result<()>
where
    B: Backend,
{
    let model: Model<B> = Model::new();
    let _shape = Shape::new([1, 6, 15]);
    //let _input = Tensor::<B, 3>::ones(_shape);
    let _input = Tensor::<B, 3>::zeros(_shape);
    let output = model.forward(_input);
    println!("{:?}", output);
    Ok(())
}

#[test]
fn my_test() {
    let _ = my_model::<NdArrayB>();
}
```

**Desktop (please complete the following information):**
 - OS: macOS
 - version: Main branch latest commit

**Additional context**

Sorry for bugging you guys again with my issues loading this model. Hopefully, it is productive beyond just my use case... Happy to provide any additional details or do additional coding if pointed in the right direction.

Thanks,
Mitchell

**Comment by antimora** [comment] 2023-08-17 01:36
@mrvollger, thanks for filing the issue ticket. I have started looking into this. 

I ran your onnx through `onnxsim` to trace the output shapes and I am sharing here with you so you can see the output shape at each node. `onnxsim revio.onnx revio-sim.onnx`



[revio-sim.onnx.zip](https://github.com/burn-rs/burn/files/12364579/revio-sim.onnx.zip)

**Comment by mrvollger** [comment] 2023-08-17 02:32
Awesome, I was looking for a way to check all of those dimensions. Good to learn about this tool. I will resume my investigation as well, I feel there is a good chance that if there is a dimension mismatch it might be happening in my conv1d code...

**Comment by mrvollger** [comment] 2023-08-17 02:57
Yep I think I made a mistake in my Conv1D code. Becuase your simulation says that the dims after the first conv1d should be [1 x 30 x 11] but in burn-import it has dims [1 X 30 X **15**] after the first conv1d. 

I will dig around to see if I can find what is likely my mistake in the conv1d. 

sorry about this!

**Comment by antimora** [comment] 2023-08-17 03:00
@mrvollger I found a bug in our Conv1d module implementation. I haven't dived in to find the root cause. It's not ONNX issue. 

Here is a unit test that fails to catch:

```rust
    #[test]
    fn verify_output_shape() {
        let conv1d1: Conv1d<TestBackend> = Conv1dConfig::new(6, 30, 1)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();

        let input = Tensor::<TestBackend, 3>::zeros([1, 6, 15]);

        let output = conv1d1.forward(input);

        assert_eq!(output.shape(), [1, 30, 11].into());
    }
```

Errors out like this:

```
running 1 test
thread 'nn::conv::conv1d::tests::verify_padding' panicked at 'assertion failed: `(left == right)`
  left: `Shape { dims: [1, 30, 15] }`,
 right: `Shape { dims: [1, 30, 11] }`', burn-core/src/nn/conv/conv1d.rs:175:9
stack backtrace:
```

I traced the output shapes and that's how I discovered by comparing the outputs:

```rust
    #[allow(clippy::let_and_return)]
    pub fn forward(&self, input1: Tensor<B, 3>) -> Tensor<B, 2> {
        println!("input1: {:?}", input1.shape());

        let conv1d1_out1 = self.conv1d1.forward(input1);
        println!("conv1d1_out1: {:?}", conv1d1_out1.shape());

        let relu1_out1 = burn::tensor::activation::relu(conv1d1_out1);
        println!("relu1_out1: {:?}", relu1_out1.shape());

        let conv1d2_out1 = self.conv1d2.forward(relu1_out1);
        println!("conv1d2_out1: {:?}", conv1d2_out1.shape());

        let relu2_out1 = burn::tensor::activation::relu(conv1d2_out1);
        println!("relu2_out1: {:?}", relu2_out1.shape());

        let conv1d3_out1 = self.conv1d3.forward(relu2_out1);
        println!("conv1d3_out1: {:?}", conv1d3_out1.shape());

        let relu3_out1 = burn::tensor::activation::relu(conv1d3_out1);
        println!("relu3_out1: {:?}", relu3_out1.shape());

        let flatten1_out1 = relu3_out1.flatten(1, 2);
        println!("flatten1_out1: {:?}", flatten1_out1.shape());

        let linear1_out1 = self.linear1.forward(flatten1_out1);
        println!("linear1_out1: {:?}", linear1_out1.shape());

        let relu4_out1 = burn::tensor::activation::relu(linear1_out1);
        println!("relu4_out1: {:?}", relu4_out1.shape());

        let linear2_out1 = self.linear2.forward(relu4_out1);
        println!("linear2_out1: {:?}", linear2_out1.shape());

        let softmax1_out1 = burn::tensor::activation::softmax(linear2_out1, 1);
        println!("softmax1_out1: {:?}", softmax1_out1.shape());

        softmax1_out1
    }
```

The output: 

```
     Running `target/debug/revio-burn`
input1: Shape { dims: [1, 6, 15] }
conv1d1_out1: Shape { dims: [1, 30, 15] }
relu1_out1: Shape { dims: [1, 30, 15] }
conv1d2_out1: Shape { dims: [1, 10, 15] }
relu2_out1: Shape { dims: [1, 10, 15] }
conv1d3_out1: Shape { dims: [1, 5, 15] }
relu3_out1: Shape { dims: [1, 5, 15] }
flatten1_out1: Shape { dims: [1, 75] }
thread 'main' panicked at '=== Tensor Operation Error ===
  Operation: 'Matmul'
  Reason:
    1. The inner dimension of matmul should be the same, but got 75 and 25. Lhs shape [1, 75], rhs shape [25, 5]. 
', /Users/dilshod/.cargo/git/checkouts/burn-acfbee6a141c1b41/8808ee2/burn-tensor/src/tensor/api/float.rs:196:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mrvollger** [comment] 2023-08-17 04:07
I will keep looking for my padding bug, but I am having trouble identifying where I went wrong. I guess I shouldn't have used a sum test case since that misses the dimensions aspect and specifically padding issues. I will keep this thread updated.

**Comment by antimora** [comment] 2023-08-17 04:10
@mrvollger I have a problem and I fixed it. It's working now. 

The issue was incorrect kernel size set. I will submit a PR in a few minutes. Running checks locally. Here is a correct output:

```rust
    #[allow(dead_code)]
    pub fn new() -> Self {
        let conv1d1 = Conv1dConfig::new(6, 30, 5)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let conv1d2 = Conv1dConfig::new(30, 10, 5)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let conv1d3 = Conv1dConfig::new(10, 5, 3)
            .with_stride(1)
            .with_padding(PaddingConfig1d::Valid)
            .with_dilation(1)
            .with_groups(1)
            .with_bias(true)
            .init();
        let linear1 = LinearConfig::new(25, 5).with_bias(true).init();
        let linear2 = LinearConfig::new(5, 2).with_bias(true).init();
        Self {
            conv1d1,
            conv1d2,
            conv1d3,
            linear1,
            linear2,
            phantom: core::marker::PhantomData,
        }
    }
    
```

Here is a test output:



```
     Running `target/debug/revio-burn`
Tensor { primitive: NdArrayTensor { array: [[0.6664351, 0.33356494]], shape=[1, 2], strides=[2, 1], layout=CFcf (0xf), dynamic ndim=2 } }

```

**Comment by antimora** [comment] 2023-08-17 04:17
https://github.com/burn-rs/burn/pull/658 fixes the bug. @mrvollger Please check out the PR locally to test if you can. This should work for you.

**Comment by mrvollger** [comment] 2023-08-17 04:47
Confirmed your PR fixes my issues locally! Thanks!

**Comment by antimora** [comment] 2023-08-17 05:15
Keeping it open till the PR is merged.

**Closed** 2023-08-17 12:41 UTC
Labels: bug
