### ISSUE TITLE
Could `burn::train::ClassificationOutput` be used in regression? Or another output structure is needed?

### ISSUE THREAD

**Issue by bioinformatist** [burn-rs/burn#373] opened 2023-05-31 08:00 UTC
### Feature description

Almost all examples (like [this](https://github.com/burn-rs/burn/blob/main/examples/mnist/src/model.rs#L113-L125)) only provide a way for classification problem. Since we must implement `burn::train::TrainStep` and `burn::train::ValidStep` for a concrete model, I'm not sure there's a proper structure (just like `ClassificationOutput<B>` in examples for classification) for their `TO` parameter when used in **regression**.

### Feature motivation

I'm working on a continuous ML framework thesedays, which make users can custom their models and training process based on Burn. For example, I have a snippet as below:

```rust
pub struct ModelConfig<B: ADBackend, M: ADModule<B> + Display + TrainStep<_, _> + ValidStep<_, _>> {
    pub work_dir: PathBuf,
    pub device: B::Device,
    pub model: M,
}
``` 

Obviously the placeholder is not allowed here, but to the second ones (as `TO` in our source code), I'm not sure which type should be used here.

BTW, I really hope it can support both classification and regression here (and maybe other type of ML missions).

### (Optional) Suggest a Solution

Shall we add a structure for regression and provide necessary methods for it? I'm not sure if there's any misunderstanding.

**Comment by nathanielsimard** [comment] 2023-05-31 13:49
`ClassificationOutput` should not be used for regression, you can create another struct similar to this one but for regression: `RegressionOutput`.

```rust
use crate::metric::{Adaptor, LossInput};
use burn_core::tensor::backend::Backend;
use burn_core::tensor::Tensor;

#[derive(new)]
pub struct RegressionOutput<B: Backend> {
    pub loss: Tensor<B, 1>,
    pub output: Tensor<B, 2>,
    pub targets: Tensor<B, 2>,
}

impl<B: Backend> Adaptor<LossInput<B>> for RegressionOutput<B> {
    fn adapt(&self) -> LossInput<B> {
        LossInput::new(self.loss.clone())
    }
}
```

For now there isn't a lot of metrics implemented, but you could add some and plug them into `burn_train` easily. You can open issues for missing metrics so we can develop that side of burn :)

**Comment by antimora** [comment] 2023-06-01 16:10
@bioinformatist for now we will close this ticket as non-actionable since it was more question than specific feature request. You can file a new issue for missing metrics. If you have further questions, please join us on Discord, we will be happy to reply to your questions promptly.

**Closed by antimora** 2023-06-01 16:10 UTC
